name: Build Page
on:
  push:
  # schedule:
  #   - cron: '0 1 * * */1'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.29

      # - run: npm run generateJson
      # - run: deno run -A script.ts

      - run: npm ci
      - run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
